### ISSUE TITLE
Information request regarding assembler

### ISSUE THREAD

**Issue by stefcamp** [chrisquince/STRONG#103]
Hi,
I would like to ask if STRONG can be used with the high-resolution graph (HRG) obtained specifically from metaSPAdes, or if it is possible to use also other assemblers such as megahit.
Thanks in advance for the information.
Sincerely
--
Stefano

**Comment by Sebastien-Raguideau** [comment]
Hi Stefano
I'm currently unaware of other sources of high resolution assembly graph. Since STRONG is basically just a snakemake, if you generate yourself a high resolution graph and the corresponding normal assembly graph, by naming them and placing them in the right folder you could have STRONG use them. 
So at the moment only SPAdes is supported, I think we are open to implementing alternate assembly options if they can propose similar high resolution graph. Do you have source for megahit based HRG? 
Best,
Seb
