### ISSUE TITLE
Co-assembly

### ISSUE THREAD

**Issue by andrewjmc** [chrisquince/STRONG#119]
I have a dataset which is too large to co-assemble on my HPC. I would like to analyse a species of interest across hundreds of human samples. I've extracted reads from the relevant genus for each sample (kraken), and tested out a co-assembly with MEGAHIT for simplicity. However, I get very short contigs (max 28k bases; shorter than a single assembly of the best covered sample). Looking at the assembly graph (k=141) you can see high complexity, and I believe that the short contigs occur because of the high variation between genomes.

![image](https://user-images.githubusercontent.com/11620733/139602892-c200754a-aed8-454f-a71b-c0a47c367315.png)

Assuming the assembly with metaSPAdes produces a similar graph and small/fragmented contigs, do you think this will be amenable to strain resolution with STRONG?

Thanks,

Andrew

**Comment by Sebastien-Raguideau** [comment]
Hi Andrew,

From the standpoint of STRONG, the size of the contigs is not important, what is important is the state of the assembly graph. Now, a thing to note is that while we use metaSPAdes, we don't go all the way up to kmer the size of the read length (141): while it tends to increase N50 it also fragments the graph (understand loss of edges) and penalise low coverages.

Then we also work on a "high resolution" assembly graph, not usually outputed by metaspades, that exist before simplifications heuristics are applied to, for instance, resolve bubble. 

For STRONG to work you would just need to be sure that you are not missing too many reads arounds the SCGs, since STRONG only focus on a select few 36 SCGs. I didn't test this strategy before but SCG are quite conserved and I would guess that kraken would be able to find theses. You could also go for some more involved approach like hmm for these SCG on 6frame translated reads.

Best,
Seb

**Comment by andrewjmc** [comment]
Thanks for this. In terms of extracting reads with kraken, the conservation of SCG within my species of interest will save us, but conservation with other species will hinder us (since reads from regions like this will be assigned above genus level).

I can check this out though within my alignment to the reference genome.

**Comment by Sebastien-Raguideau** [comment]
I would not worry too much about this either :) While assembly cannot guaranty to separate sequence at  the level of strains, it can at least do so at the level of species. Also, to be clear there is a binning step after assembly and before strain deconvolution through bayespath. So, no issues with recruiting more than one species. The base pipeline assume this is the case.

**Comment by andrewjmc** [comment]
OK, really helpful, thanks!
