### ISSUE TITLE
Maybe we need to add libiconv to yaml

### ISSUE THREAD

**Issue by chrisquince** [chrisquince/STRONG#98]
This is certainly needed in Ubuntu 16.04

**Comment by Sebastien-Raguideau** [comment]
conda_env.yaml works fine for the results part with last iteration of change. 
--> added libiconv
--> reshape2 instead of reshape
--> channel r before channel conda-forge (conda-forge recipe fail)

BUT I had to implement an unsavory fix on R not finding library, there is a need to manually symlink 1 lib to another location. 
Instead of putting it in install readme, i created a rule in results. Not sure how robust, that is.

**Comment by Sebastien-Raguideau** [comment]
Just to precise, I spent 1h trying different requirement of library to not do that. But, that seems to be the best answer at the moment
